### ISSUE TITLE
search history

### ISSUE THREAD

**Issue by damnskippy** [haya14busa/incsearch.vim#59] opened 2015-01-14 17:07 UTC
I'm running into the following issue with respect to search history.
Perhaps I'm doing something wrong or missing some configuration settings?
At the search prompt I use <C-P> or <Up> to look up previously used search patterns.
With incsearch.vim, this history is now filled up with every incremental search and breaks the history browsing.

For instance, if you search for the word "default"

Default vim:
- search history via command "q/" shows only one entry for "default"
- using <Up> at the search prompt will insert "default"

Incsearch.vim:
- search history via command "q/" shows:
  - def
  - defa
  - defau
  - defaul
  - default
  - default
- using <Up> at this point takes you through each sub-pattern before reaching the actual previous pattern

**Comment by haya14busa** [comment] 2015-01-14 17:13
I cannot reproduce this. Could you tell me more detail information such as vim version.

**Comment by damnskippy** [comment] 2015-01-14 17:33
I'm using vim version 7.4 (compiled about 6 months ago).
Without incsearch I don't have this issue.
If I'm the only one running into this, then I wonder if something in my setup is conflicting with incsearch. :(

**Comment by haya14busa** [comment] 2015-01-14 17:52
Please include patch number to describe version like `7.4.xxx`. You can see it with `:version`.

Could you make the minimal vimrc and minimal reproduction steps?

**Comment by damnskippy** [comment] 2015-01-14 20:56
I'll try to narrow it down for you soon.

**Comment by komuta** [comment] 2015-01-15 09:41
Hi, I ran into the same problem. Tested with the latest incsearch version.
Issue is present on Ubuntu Trusty version, v7.4.52, but not in latest (v7.4.580). Not present on OS X with homebrew current version (v7.4.488).

**Comment by damnskippy** [comment] 2015-01-15 14:44
@komuta Thanks for those data points.
Maybe I need to try the latest version too and see if the problem goes away.
I had compiled from the sources myself - maybe I should try updating and see if it helps.
At least it's good to hear that I'm not the only one seeing this (i.e. not specific to my environment).

BTW, is it easier for you to narrow the steps that @haya14busa asked for using the Ubuntu version where you see this issue?
Thanks again.

**Comment by haya14busa** [comment] 2015-01-15 18:52
@komuta Thanks for the info:)

@damnskippy Please tell me the vim version including patch number. I guess there was unexpected behavior or bug in old vim and it's fixed in the current version. According to @komuta's report, the fixed patch should be between v7.4.52 and v7.4.480. If you ( @damnskippy ) can report the patch number which reproduce this issue, we can narrow the exact patch number which fix this problem.

**Comment by damnskippy** [comment] 2015-01-15 19:06
@haya14busa this is all the version info I get from vim --version
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar  5 2014 09:52:01)
[...]
So the code is fairly old and I owe it to you and myself to update to the latest.
Until then, I could go ahead and close this issue if you'd like to me.

**Comment by haya14busa** [comment] 2015-01-15 19:25
Second line should include patch number like this. Do not omit the important line;)

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 19 2014 00:30:11)
Included patches: 1-560
```

**Comment by damnskippy** [comment] 2015-01-15 21:13
But there is no mention of anything related to patch anywhere in the output.
I certainly wouldn't have missed to include if this information was there.
FWIW, here's a few more lines:
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar  5 2014 09:52:01)
Compiled by damnskippy@spartanhost
Huge version with GTK2 GUI.  Features included (+) or not (-):
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    +mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
[...]

**Comment by damnskippy** [comment] 2015-01-16 01:15
Good news - compiled from the latest sources and I no longer see this issue.
And I see the patch info displayed in the version output as well, FWIW.
Thanks for your time - I'll go ahead and close this issue now.

$vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 15 2015 20:09:38)
Included patches: 1-580
[...]

**Comment by komuta** [comment] 2015-01-16 08:37
Hi, sorry I've been busy, but since yesterday I've given some thoughts about it. Since some of us saw the bug appear in 7.0.52, there must be a regression at some point in the plugin. I narrowed it down with git bisect, and identified the following commit: a2ccf86ce44b928a4d50b2f288911d2c00161826.
@haya14busa, could you check if you could fix this ? Ubuntu Trusty is still LTS, and it would be nice if we could use the plugin with the vim version packaged with the system, without having to compile/install a newer version.
By the way, I also narrowed down the fix in vim, if it can be of any help: https://code.google.com/p/vim/source/detail?r=6367a766027d

**Comment by haya14busa** [comment] 2015-01-16 21:35
>By the way, I also narrowed down the fix in vim, if it can be of any help: https://code.google.com/p/vim/source/detail?r=6367a766027d

@komuta ...! Thanks for the inverstigation :+1:
I'll look into it.

**Comment by achalddave** [comment] 2016-06-16 22:47
Is there any workaround for this? I'm seeing this issue as well...

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 21 2016 21:22:17)
Compiled by [removed]
Huge version with GTK2 GUI.  Features included (+) or not (-):
...
```

**Comment by haya14busa** [comment] 2016-12-25 04:20
I don't have any plan to work on this. Please update Vim.

**Closed by haya14busa** 2016-12-25 04:20 UTC
